### ISSUE TITLE
Winget store not working, showing error.

### ISSUE THREAD

**Issue by Jakeverse** [wherewhere/WinGet-Store#4]
### Describe the bug

I have been trying to use this app, but it throws this error.

My internet working good, even tried with vpn but not work. I don't know what causing this issue.
Please let me know what causing this problem. I have tried old version a month ago and thought that this version maybe addressed and fixed this issue but still throws same error. 

Windows version: 11 22000.9 

### Steps to reproduce the bug

1. open app
2. throws error

### Screenshots

Video Link: https://drive.google.com/file/d/1Usc_pU44D6zEXSrEOBvteSZaPJBqF-89/view?usp=sharing

### App version

0.0.1

### Windows version

Windows 11 version 21H2 (22000)

### Device

Desktop

**Comment by wherewhere** [comment]
Fixed https://github.com/wherewhere/WinGet-Store/commit/652a28010cad428fc368580380871a8026a0f0e5

**Comment by Jakeverse** [comment]
Thank you so much, now working good. 🥰

https://prnt.sc/VexbSO1FnkMx
